# Generated by Django 3.1.4 on 2021-01-05 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_user_call_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='registration_date',
        ),
    ]
