# Generated by Django 3.1.4 on 2021-01-05 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_user_registration_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='chat_name',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='chat',
            name='chat_type',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
